name: Deploy

on:
  push:
    branches:
      - main

jobs:
  kotest:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant Permissions to gradlew
        run: |
          gradle wrapper
          chmod +x gradlew

      - name: Build
        env:
          DB_ADMIN_IP: ${{ secrets.DB_ADMIN_IP }}
          DB_ADMIN_NAME: ${{ secrets.DB_ADMIN_NAME }}
          DB_ADMIN_PORT: ${{ secrets.DB_ADMIN_PORT }}
          DB_ADMIN_PWD: ${{ secrets.DB_ADMIN_PWD }}
          DB_ADMIN_USER: ${{ secrets.DB_ADMIN_USER }}
          TEST_DB_ID: ${{ secrets.TEST_DB_ID }}
        run: ./gradlew build

      - name: Docker build
        run: ./gradlew bootBuildImage

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Publish to Docker Hub
        run: |
          docker push testadirapa/kabot-api