name: Deploy

on:
  push:
    branches:
      - main

jobs:
  kotest:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant Permissions to gradlew
        run: |
          gradle wrapper
          chmod +x gradlew

      - name: Build
        env:
          DB_ADMIN_IP: ${{ secrets.DB_ADMIN_IP }}
          DB_ADMIN_NAME: ${{ secrets.DB_ADMIN_NAME }}
          DB_ADMIN_PORT: ${{ secrets.DB_ADMIN_PORT }}
          DB_ADMIN_PWD: ${{ secrets.DB_ADMIN_PWD }}
          DB_ADMIN_USER: ${{ secrets.DB_ADMIN_USER }}
          TEST_DB_ID: ${{ secrets.TEST_DB_ID }}
        run: ./gradlew build

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build Image and Publish to Docker Hub
        run: |
          ./gradlew bootBuildImage --imageName=testadirapa/kabot-api:${{ secrets.VERSION }}
          docker push testadirapa/kabot-api:${{ secrets.VERSION }}

      - name: Run Api on Remote Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker rm -f -v kabot-api
            docker run -d --name kabot-api -p 16170:16170 --env-file /home/waghambot/kabotapi.env testadirapa/kabot-api:${{ secrets.VERSION }}
