name: Deploy

on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'


jobs:
  deploy_on_docker:
    name: Deploy
    if: github.event.pull_request.merged == true && (contains(github.event.pull_request.labels.*.name, 'major') || contains(github.event.pull_request.labels.*.name, 'minor') || contains(github.event.pull_request.labels.*.name, 'patch'))
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant Permissions to gradlew
        run: |
          gradle wrapper --gradle-version=7.5
          chmod +x gradlew

      - name: Build
        env:
          DB_ADMIN_IP: ${{ secrets.DB_ADMIN_IP }}
          DB_ADMIN_NAME: ${{ secrets.DB_ADMIN_NAME }}
          DB_ADMIN_PORT: ${{ secrets.DB_ADMIN_PORT }}
          DB_ADMIN_PWD: ${{ secrets.DB_ADMIN_PWD }}
          DB_ADMIN_USER: ${{ secrets.DB_ADMIN_USER }}
          TEST_DB_ID: ${{ secrets.TEST_DB_ID }}
          MODULE_LOCK: ${{ secrets.MODULE_LOCK }}
          RELEASE_GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
        run: ./gradlew build

      - name: Creation new version (Major) 🏷️
        if: ${{ contains(github.event.pull_request.labels.*.name, 'major') }}
        run: ./gradlew incrementVersion --versionIncrementType=MAJOR --versionIncrementBranch=main -PgitUserName=TestaDiRapa -PgitUserEmail=v.c.pierro@gmail.com
      - name: Creation new version (Minor) 🏷️
        if: ${{ contains(github.event.pull_request.labels.*.name, 'minor') }}
        run: ./gradlew incrementVersion --versionIncrementType=MINOR --versionIncrementBranch=main -PgitUserName=TestaDiRapa -PgitUserEmail=v.c.pierro@gmail.com
      - name: Creation new version (Patch) 🏷️
        if: ${{ contains(github.event.pull_request.labels.*.name, 'patch') }}
        run: ./gradlew incrementVersion --versionIncrementType=PATCH --versionIncrementBranch=main -PgitUserName=TestaDiRapa -PgitUserEmail=v.c.pierro@gmail.com

      - name: Save version to env
        run: echo "NEW_VERSION=$(gradle printLibVersion | grep -o '[0-9]\+.[0-9]\+.[0-9]\+')" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build Image and Publish to Docker Hub
        env:
          DB_ADMIN_IP: ${{ secrets.DB_ADMIN_IP }}
          DB_ADMIN_NAME: ${{ secrets.DB_ADMIN_NAME }}
          DB_ADMIN_PORT: ${{ secrets.DB_ADMIN_PORT }}
          DB_ADMIN_PWD: ${{ secrets.DB_ADMIN_PWD }}
          DB_ADMIN_USER: ${{ secrets.DB_ADMIN_USER }}
          TEST_DB_ID: ${{ secrets.TEST_DB_ID }}
          MODULE_LOCK: ${{ secrets.MODULE_LOCK }}
          RELEASE_GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
        run: |
          ./gradlew build bootBuildImage --imageName=testadirapa/kabot-api:${{ env.NEW_VERSION }}
          docker push testadirapa/kabot-api:${{ env.NEW_VERSION }}

      - name: Run Api on Remote Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker rm -f -v kabot-api
            docker image prune -a -f
            docker run -d --name kabot-api -p 16170:16170 --env-file /home/waghambot/kabotapi.env testadirapa/kabot-api:${{ env.NEW_VERSION }}
