name: Test

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  kotest:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Grant Permissions to gradlew
        run: |
          gradle wrapper --gradle-version=7.5
          chmod +x gradlew

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Test
        env:
          DB_ADMIN_IP: ${{ secrets.DB_ADMIN_IP }}
          DB_ADMIN_NAME: ${{ secrets.DB_ADMIN_NAME }}
          DB_ADMIN_PORT: ${{ secrets.DB_ADMIN_PORT }}
          DB_ADMIN_PWD: ${{ secrets.DB_ADMIN_PWD }}
          DB_ADMIN_USER: ${{ secrets.DB_ADMIN_USER }}
          TEST_DB_ID: ${{ secrets.TEST_DB_ID }}
          MODULE_LOCK: ${{ secrets.MODULE_LOCK }}
          RELEASE_GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
        run: ./gradlew test